config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  get 'main/index'

  resources :books do
    member do
      get :delete
    end
  end

  # get 'tasks/index'
  # get 'tasks/new'
  # get 'tasks/edit'
  # get 'tasks/show'
  # get 'tasks/delete'
  # get 'categories/index'
  # get 'categories/show'
  # get 'categories/new'
  # get 'categories/edit'
  # get 'categories/delete'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.order(:position)
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @count = Book.count
    @book = Book.new(position: @count + 1)
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to books_path
    else
      # The 'new' action is NOT being called here
      # Assign any instance variables needed
      # @count = Book.count
      flash[:notice] = 'Title can\'t be blank'
      render('new')
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book was successfully updated.'
      redirect_to book_path(@book)
    else
      render('edit')
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = 'Book was successfully destroyed.'
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(
      :title,
    )
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    # render('index')
  end

  def about
    @created_by = "Kevin"
    @id = params['id']
    @page = params[:page]
    # render('about')
  end

  def hello
    redirect_to(action: 'index')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/books/_form.html.erb
<table summary="Book form fields">
  <tr>
    <th>Title</th>
    <td><%= f.text_field :title, id: 'book_title'%></td>
  </tr>
</table>

app/views/books/delete.html.erb
<%= link_to("Back to List", books_path, class: 'back-link') %>

<div class="books delete">
  <h2>Delete Book</h2>

  <%= form_for(@book, method: 'delete') do |f| %>
    <% # url: book_path(@book), method: 'delete' %>

    <p>Are you sure you want to permanently delete this book?</p>
    <p><%= @book.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Book") %>
    </div>

  <% end %>
</div>

app/views/books/edit.html.erb
<%= link_to("Back to List", books_path, :class => 'back-link') %>

<div class="books edit">
  <h2>Edit book</h2>

  <%= form_for(@book) do |f| %>
    <% # url: book_path(@book), method: 'patch' %>

    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit("Edit book") %>
    </div>

  <% end %>
</div>

app/views/books/index.html.erb
<div class="books index">
  <h2>Book Collection</h2>
  <% if flash[:notice].present? %>
    <div class="notice">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <hr>
  <%= link_to("Add New book", new_book_path, class: 'action new') %>

  <table class="listing" summary="book list" style="width: 100%;">
    <tr class="header">
      <td><h3>Title</h3></td>
      
      <td><h3>Actions</h3></td>
    </tr>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td class="actions">
        <%= link_to("Show", book_path(book), class: 'action show') %>
        <%= link_to("Edit", edit_book_path(book), class: 'action edit') %>
        <%= link_to("Delete", delete_book_path(book), class: 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
  
</div>

app/views/books/new.html.erb
<%= link_to("Back to List", books_path, :class => 'back-link') %>

<div class="books new">
  <h2>Create book</h2>
  <% if flash[:notice].present? %>
    <div class="notice">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <%= form_for(@book) do |f| %>
    <% # url: books_path, method: 'post' %>

    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit("Create book", id: 'Create Book') %>
    </div>

  <% end %>
</div>

app/views/books/show.html.erb
<%= link_to("Back to List", books_path, class: 'back-link') %>

<div class="books show">
  <h2>Show book</h2>

  <div class="actions">
    <%= link_to('Edit', edit_book_path(@book)) %>
    <%= link_to('Delete', delete_book_path(@book)) %>
  </div>

  <table summary="book detail view">
    <tr>
      <th>Title</th>
      <td><%= @book.title %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @book.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @book.updated_at %></td>
    </tr>
  </table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/about.html.erb
<h2>About</h2>

<p>Description of the book collection.</p>
<p>Created by <%= @created_by %></p>

ID: <%= @id %><br />
Page: <%= @page %><br />

app/views/main/index.html.erb
<h1>Book Collection</h1>
<p>This is an application for managing a book collection.</p>

<%= link_to('Books', books_path(page: 1)) %><br />

<%= link_to('About', {action: 'about', page: 5, id: 20}) %><br />